theme: jekyll-theme-minimal
title: Polycule
description: Electronics, music instruments
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: One-shot
    url: one-shot
  - title: Moduled Nano
    url: moduled-nano
  - title: Moduled Rack
    url: moduled-rack
  - title: Resources
    url: resources
  - title: PO-24 Cheat Sheet
    url: https://github.com/kbsezginel/polycule/blob/master/assets/img/PO-24-cheat-sheet.svg
