theme: jekyll-theme-minimal
title: Polycule
description: Electronics, music instruments
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: One-shot
    url: one-shot
  - title: Resources
    url: resources
  - title: PO-24 Cheat Sheet
    url: https://raw.githubusercontent.com/kbsezginel/polycule/master/assets/img/PO-24-cheat-sheet.svg
